[package]
name = "chacha"
version = "0.2.0"
authors = ["Jonas Wolf"]
edition = "2018"

[dev-dependencies]
criterion = "0.2.5"

[profile.bench]
lto = true

[[bench]]
name = "chacha_bench"
harness = false
