[package]
name = "chacha"
version = "0.2.0"
authors = ["Jonas Wolf"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[profile.bench]
lto = true

[lib]
bench = false

[[bench]]
name = "chacha_bench"
harness = false
