# This is a basic workflow to help you get started with Actions

name: Code Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  measure:
    runs-on: ubuntu-latest

    # Install LLVM
    steps:
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 12

      # Install nightly rust toolchain (required to use LLVM code coverage instrumentation)
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Build and execute tests
      - name: Build and test
        env: 
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Clink-dead-code -Copt-level=0 -Ccodegen-units=1 -Zpanic_abort_tests -Cpanic=abort -Cpanic=abort -Coverflow-checks=off -Zinstrument-coverage"
          RUSTDOCFLAGS: "-Cpanic=abort"
          LLVM_PROFILE_FILE: "profile.profraw"
        run: |
          cargo +nightly build
          cargo +nightly test --no-run --message-format=json | jq -r "select(.profile.test == true) | .filenames[]" | grep -v dSYM - > filenames.txt
          cargo +nightly test 

      # Extracte code coverage information
      - name: Extract Code Coverage
        run: |
          /usr/lib/llvm-12/bin/llvm-profdata merge -sparse -o profile.profdata profile.profraw 
          /usr/lib/llvm-12/bin/llvm-cov export --format=lcov -instr-profile=profile.profdata `cat filenames.txt` > lcov.info
      
      # Upload to codecov.io 
      - uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
        

